# $FreeBSD$

PORTNAME=	freewebos-cjson
PORTVERSION=	1.0b
CATEGORIES=	devel

MAINTAINER=	penzin.dev@gmail.com
COMMENT=	Edition of Json-C library used in WebOS

LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	FreeWebOS
GH_PROJECT=	cjson
GH_TAGNAME=	1.8.1
GH_COMMIT=	29a8d88

USES_AUTOTOOLS=	autoconf
INSTALL_TARGET=	install

.include <bsd.port.mk>
