# $FreeBSD$

PORTNAME=	cmake-modules-webos
PORTVERSION=	1.0b
CATEGORIES=	devel

MAINTAINER=	penzin.dev@gmail.com
COMMENT=	Cmake modules for WebOS, needed for building WebOS cmake ports

LICENSE=	APACHE20

USE_GITHUB=	yes
GH_ACCOUNT=	FreeWebOS
GH_TAGNAME=	submissions/19
GH_COMMIT=	5b5c38c

USES=		cmake:outsource
INSTALL_TARGET=	install

.include <bsd.port.mk>
